apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: rcklryuv4-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/rcklryuv4-dotnet-basic-gitops